### ISSUE TITLE
Not working with tensorflow 2.4.1

### ISSUE THREAD

**Issue by Luca409** [MaybeShewill-CV/lanenet-lane-detection#501]
Title mostly says it all.  I don't know much about tensorflow, but I've been reading about how a lot of things were deprecated between 1 and 2.  

After installing requirements.txt (and commenting out tensorflow_gpu since it's incompatible with tensorflow2)

I get

> AttributeError: module 'tensorflow' has no attribute 'placeholder'

when trying to run

`python tools/test_lanenet.py ...`

Perhaps the README needs an update as well?

**Comment by MaybeShewill-CV** [comment]
@Luca409 Sorry for the misleading information from requirement.txt. New requirement.txt has been updated. Tensorflow 2 is not supported for now:)

**Comment by Luca409** [comment]
After throwing some __init__.py around, got this working without needing Anaconda and using peen. Thanks!
